#!/usr/bin/env python3
"""Extract the Power Platform API surface from the decompiled `pac` CLI.

`Microsoft.PowerPlatform.Management` — one of the assemblies shipped inside the
Power Platform CLI — is Microsoft's own **Kiota-generated** client for this API.
Kiota generates from OpenAPI, so the assembly is a mechanical projection of the
internal OpenAPI document behind the Learn pages: a second, independent view of
the same source the docs mirror in `docs/` is generated from.

That makes it worth parsing rather than reading. Kiota's output is regular in
exactly the places that matter:

    public class FinopsadminsettingsRequestBuilder : BaseRequestBuilder
    {
        public class FinopsadminsettingsRequestBuilderGetQueryParameters
        {
            [QueryParameter("api%2Dversion")] public string? ApiVersion { get; set; }
        }
        public FinopsadminsettingsRequestBuilder(...)
            : base(requestAdapter,
                   "{+baseurl}/dynamics/environments/{environmentId}/finopsadminsettings"
                   "?api-version={api%2Dversion}", pathParameters) { }
        public async Task<FinOpsAdminSettingsResponse?> PutAsync(
            UpdateFinOpsAdminSettingsRequestBody body, ...) { ... }
        public RequestInformation ToPutRequestInformation(...) {
            new RequestInformation(Method.PUT, base.UrlTemplate, base.PathParameters);
        }
    }

So one builder class yields: the RFC 6570 URL template (path, path parameters,
required `api-version`, and each optional query parameter as `{&name*}`), the
verbs it supports, the request-body model per verb, the response model per verb,
and the error model per status code. `Models/*.cs` yields the schemas: the
`Serialize` method maps wire name to C# property, the property declarations give
the type, and enums carry `[EnumMember(Value = "...")]`.

Two Kiota quirks the parser has to respect:

  * Percent escapes in template and attribute names are real: `{api%2Dversion}`
    is `api-version` and `{environment%2Did}` is `environment-id` (which is how
    environmentmanagement — and only environmentmanagement — spells it).
  * A verb whose query parameters are a subset of the class's may build its own
    template inline instead of using `base.UrlTemplate`. The method-level
    template wins; the class-level one is the union over all verbs.

Unlike `bapi/scripts/extract.py`, which seeds a hand-owned spec from the
Terraform provider's Go client, this script never writes the spec: `ppapi`'s
`oas/openapi.json` is regenerated by `oas.py` from `docs/` on every run, so
everything this script finds has to land in `enrichment.json` to survive. It is
therefore an inventory and a drift audit, and the `--check` diff is the thing
you run after a mirror commit.

    pac_extract.py <decompiled-root>              # JSON inventory on stdout
    pac_extract.py <decompiled-root> --check      # diff against oas/openapi.json
    pac_extract.py <decompiled-root> --schemas    # OAS schema fragments only

<decompiled-root> is the folder holding `Microsoft.PowerPlatform.Management.csproj`
(or any parent of it). Evidence grade: this is a shipped first-party client, not
a live observation — see the `x-source: pac-cli` marking in enrichment.json.
"""
import json
import pathlib
import re
import sys
import urllib.parse

VERBS = ("Get", "Post", "Put", "Patch", "Delete")

# Kiota writer call -> OAS schema for the value it writes
WRITER_SCALARS = {
    "WriteStringValue": {"type": "string"},
    "WriteBoolValue": {"type": "boolean"},
    "WriteIntValue": {"type": "integer", "format": "int32"},
    "WriteLongValue": {"type": "integer", "format": "int64"},
    "WriteDoubleValue": {"type": "number", "format": "double"},
    "WriteGuidValue": {"type": "string", "format": "uuid"},
    "WriteDateTimeOffsetValue": {"type": "string", "format": "date-time"},
}

CS_SCALARS = {
    "string": {"type": "string"},
    "bool": {"type": "boolean"},
    "int": {"type": "integer", "format": "int32"},
    "long": {"type": "integer", "format": "int64"},
    "double": {"type": "number", "format": "double"},
    "float": {"type": "number", "format": "float"},
    "decimal": {"type": "number"},
    "Guid": {"type": "string", "format": "uuid"},
    "DateTimeOffset": {"type": "string", "format": "date-time"},
    "Date": {"type": "string", "format": "date"},
    "Time": {"type": "string", "format": "time"},
    "TimeSpan": {"type": "string", "format": "duration"},
    "byte[]": {"type": "string", "format": "byte"},
    "Stream": {"type": "string", "format": "binary"},
    "UntypedNode": {},
}

TEMPLATE_RE = re.compile(r'base\(\s*requestAdapter,\s*"([^"]+)"', re.S)
BUILDER_CLASS_RE = re.compile(r"public class (\w+RequestBuilder)\s*:\s*BaseRequestBuilder")
REQINFO_RE = re.compile(
    r"public RequestInformation To(\w+)RequestInformation\((.*?)\)\s*\{", re.S)
METHOD_CALL_RE = re.compile(
    r'new RequestInformation\(Method\.(\w+),\s*(base\.UrlTemplate|"([^"]*)")')
ASYNC_RE = re.compile(r"public async Task(?:<([\w<>?,\[\]\. ]+)>)?\s+(\w+)Async\(", re.S)
ERRMAP_RE = re.compile(r'"(\d{3}|XXX)",\s*(\w+)\.CreateFromDiscriminatorValue')
PROP_RE = re.compile(r"public\s+([\w<>?,\[\]\. ]+?)\s+(\w+)\s*\{\s*get;\s*set;\s*\}")


def unescape(name: str) -> str:
    """Kiota percent-escapes template and query-parameter names: api%2Dversion."""
    return urllib.parse.unquote(name)


def parse_template(template: str):
    """RFC 6570 template -> (path, path params, {query name: required}).

    "{+baseurl}/x/{envId}/y?api-version={api%2Dversion}{&%24skipToken*}"
      -> ("/x/{envId}/y", ["envId"], {"api-version": True, "$skipToken": False})
    """
    body = template.replace("{+baseurl}", "")
    path, _, query = body.partition("?")
    path = re.sub(r"\{([^}]+)\}", lambda m: "{" + unescape(m.group(1)) + "}", path)
    path_params = re.findall(r"\{([^}]+)\}", path)
    params = {}
    for name in re.findall(r"([\w%$@.-]+)=\{[^}]*\}", query):  # required: name={value}
        params[unescape(name)] = True
    for group in re.findall(r"\{&([^}]*)\}", query):  # optional: {&a*,b*}
        for name in group.split(","):
            params.setdefault(unescape(name.rstrip("*")), False)
    return path, path_params, params


def strip_type(cs: str) -> str:
    return cs.strip().rstrip("?").strip()


def cs_type_to_schema(cs: str, models: set):
    """A C# type from a Kiota model -> an OAS schema fragment."""
    cs = strip_type(cs)
    m = re.match(r"^(?:List|IEnumerable|ICollection)<(.+)>$", cs)
    if m:
        return {"type": "array", "items": cs_type_to_schema(m.group(1), models)}
    m = re.match(r"^(?:IDictionary|Dictionary)<\s*string\s*,\s*(.+)>$", cs)
    if m:
        return {"type": "object", "additionalProperties": cs_type_to_schema(m.group(1), models)}
    cs = cs.rsplit(".", 1)[-1]
    if cs in CS_SCALARS:
        return dict(CS_SCALARS[cs])
    if cs in ("object", "IParsable"):
        return {"type": "object"}
    models.add(cs)
    return {"$ref": f"#/components/schemas/{cs}"}


def find_body(text: str, open_idx: int) -> str:
    """Text of the brace-delimited block whose opening brace is at or after open_idx."""
    i = text.index("{", open_idx)
    depth, j = 0, i
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1:j]
        j += 1
    return text[i + 1:]


def parse_query_classes(text: str, builder: str):
    """{Builder}{Verb}QueryParameters -> {wire name: {"type": ..., "cs": ...}}.

    Kiota emits [QueryParameter("...")] only when the wire name differs from the
    C# property name, so a bare property means the wire name is PascalCase
    (`ValidateOnly`), not camelCase.
    """
    out = {}
    for verb in VERBS:
        m = re.search(rf"public class {re.escape(builder)}{verb}QueryParameters\b", text)
        if not m:
            continue
        body = find_body(text, m.end())
        params = {}
        for chunk in re.finditer(
                r'(?:\[QueryParameter\("([^"]+)"\)\]\s*)?public\s+([\w<>?,\[\]\. ]+?)\s+(\w+)\s*\{\s*get;',
                body):
            attr, cs, prop = chunk.group(1), chunk.group(2), chunk.group(3)
            wire = unescape(attr) if attr else prop
            params[wire] = strip_type(cs)
        if params:
            out[verb.upper()] = params
    return out


def parse_builder(path: pathlib.Path, root: pathlib.Path, models: set):
    text = path.read_text(encoding="utf-8", errors="replace")
    if "new RequestInformation(Method." not in text:
        return []  # navigation-only builder: no operation of its own
    cm = BUILDER_CLASS_RE.search(text)
    tm = TEMPLATE_RE.search(text)
    if not cm or not tm:
        return []
    builder, class_template = cm.group(1), tm.group(1)
    query_classes = parse_query_classes(text, builder)

    # response type and error mapping come from the *Async wrappers
    responses, errors = {}, {}
    for am in ASYNC_RE.finditer(text):
        verb = am.group(2).upper()
        if verb not in ("GET", "POST", "PUT", "PATCH", "DELETE"):
            continue
        responses[verb] = strip_type(am.group(1)) if am.group(1) else None
        errors[verb] = dict(ERRMAP_RE.findall(find_body(text, am.end())))

    ops = []
    for rm in REQINFO_RE.finditer(text):
        signature = rm.group(2)
        body = find_body(text, rm.end() - 1)
        call = METHOD_CALL_RE.search(body)
        if not call:
            continue
        verb = call.group(1).upper()
        # a verb may narrow the class template to just its own query parameters
        template = call.group(3) if call.group(3) is not None else class_template
        route, path_params, query = parse_template(template)

        bm = re.match(r"\s*([\w<>?,\[\]\. ]+?)\s+body\s*,", signature)
        content = re.search(r'SetContentFrom\w+\(base\.RequestAdapter, "([^"]+)"', body)
        accept = re.search(r'Headers\.TryAdd\("Accept", "([^"]+)"', body)

        typed = query_classes.get(verb, {})
        ops.append({
            "namespace": path.relative_to(root).parts[3].lower(),
            "method": verb,
            "path": route,
            "template": template,
            "pathParams": path_params,
            "query": [{"name": n,
                       "required": req,
                       "type": typed.get(n, "string")}
                      for n, req in query.items()],
            "requestType": strip_type(bm.group(1)) if bm else None,
            "requestContentType": content.group(1) if content else None,
            "responseType": responses.get(verb),
            "accept": (accept.group(1).split(",")[0].strip() if accept else None),
            "errors": errors.get(verb, {}),
            "builder": str(path.relative_to(root)),
        })
        for t in (ops[-1]["requestType"], ops[-1]["responseType"], *ops[-1]["errors"].values()):
            if t:
                cs_type_to_schema(t, models)
    return ops


def parse_composed_type(text: str, name: str, models: set):
    """An `IComposedTypeWrapper` -> oneOf with a discriminator.

    Kiota renders an OpenAPI `oneOf` as a wrapper class holding one nullable
    property per variant, plus a factory that switches on the discriminator:

        string value = parseNode.GetChildNode("$type")?.GetStringValue();
        if ("where".Equals(value, ...)) clause.WhereClause = new WhereClause();

    which inverts exactly back to `discriminator: {propertyName, mapping}`. The
    docs lose this shape completely — both unions land in the spec as x-stubs.
    """
    prop = re.search(r'parseNode\.GetChildNode\("([^"]+)"\)', text)
    mapping = {}
    for wire, variant in re.findall(
            r'"([^"]+)"\.Equals\(value, StringComparison\.OrdinalIgnoreCase\)\)\s*\{\s*'
            r"\w+\.\w+ = new (\w+)\(\)", text, re.S):
        mapping[wire] = f"#/components/schemas/{variant}"
        models.add(variant)
    if not mapping:
        return {"type": "object"}
    schema = {"oneOf": [{"$ref": r} for r in dict.fromkeys(mapping.values())]}
    if prop:
        schema["discriminator"] = {"propertyName": prop.group(1), "mapping": mapping}
    return schema


def parse_model(path: pathlib.Path, models: set):
    """One Models/*.cs -> (name, OAS schema). Enums and classes both."""
    text = path.read_text(encoding="utf-8", errors="replace")
    em = re.search(r"public enum (\w+)", text)
    if em:
        values = re.findall(r'\[EnumMember\(Value = "([^"]*)"\)\]', text)
        return em.group(1), {"type": "string", "enum": values}
    cm = re.search(r"public class (\w+)\s*:\s*([\w, ]+)", text)
    if not cm:
        return None, None
    name = cm.group(1)
    if "IComposedTypeWrapper" in text:
        return name, parse_composed_type(text, name, models)
    decl = {}  # C# property name -> C# type
    for pm in PROP_RE.finditer(text):
        decl[pm.group(2)] = pm.group(1)
    props = {}
    sm = re.search(r"public (?:virtual|override) void Serialize\(", text)
    if sm:
        body = find_body(text, sm.end())
        # writer.WriteXValue("wireName", CsProperty) — declaration order preserved
        for wm in re.finditer(r'writer\.(Write\w+)\("([^"]*)",\s*([\w.]+)\)', body):
            call, wire, prop = wm.group(1), wm.group(2), wm.group(3)
            if call in WRITER_SCALARS:
                schema = dict(WRITER_SCALARS[call])
            elif call == "WriteCollectionOfPrimitiveValues":
                schema = cs_type_to_schema(decl.get(prop, "List<string>"), models)
            else:  # object / enum / collection thereof: the declaration knows the type
                schema = cs_type_to_schema(decl.get(prop, "object"), models)
            props[wire] = schema
    schema = {"type": "object", "properties": props} if props else {"type": "object"}
    if "IAdditionalDataHolder" not in text:
        schema["additionalProperties"] = False
    # Kiota renders OpenAPI inheritance as a C# base class, and the derived
    # Serialize writes only the properties the subtype adds (it calls
    # base.Serialize first) — which is exactly allOf. ApiException is Kiota's own
    # error-wrapper base, not a schema, so it is not an ancestor to model.
    base = cm.group(2).split(",")[0].strip()
    if base not in ("ApiException", "IParsable", "IAdditionalDataHolder",
                    "IComposedTypeWrapper"):
        models.add(base)
        schema = {"allOf": [{"$ref": f"#/components/schemas/{base}"}, schema]}
    return name, schema


def find_root(start: pathlib.Path) -> pathlib.Path:
    """The Microsoft.PowerPlatform.Management project folder, from it or a parent."""
    if (start / "Microsoft.PowerPlatform.Management.csproj").exists():
        return start
    hits = sorted(start.glob("**/Microsoft.PowerPlatform.Management.csproj"))
    if not hits:
        sys.exit(f"no Microsoft.PowerPlatform.Management.csproj under {start}")
    return hits[0].parent


def extract(start: pathlib.Path):
    root = find_root(start.expanduser())
    src = root / "Microsoft" / "PowerPlatform" / "Management"
    models = set()
    ops = []
    for f in sorted(src.glob("**/*RequestBuilder.cs")):
        ops.extend(parse_builder(f, root, models))
    # most models live in Models/, but Kiota emits a body/response type that is
    # declared inline in the OpenAPI (rather than as a named component) beside
    # the builder that uses it — e.g. Settings/SettingsPatchRequestBody.cs
    schemas = {}
    files = sorted((src / "Models").glob("*.cs")) + [
        f for f in sorted(src.glob("**/*.cs"))
        if f.parent.name != "Models" and not f.name.endswith("RequestBuilder.cs")
        and (f.name.endswith("RequestBody.cs") or f.name.endswith("Response.cs"))]
    for f in files:
        name, schema = parse_model(f, models)
        if name:
            schemas.setdefault(name, schema)
    ver = re.search(r'public const string ApiVersion = "([^"]+)"',
                    (src / "ApiVersionHandler.cs").read_text(encoding="utf-8"))
    ops.sort(key=lambda o: (o["path"], o["method"]))
    return {
        "apiVersion": ver.group(1) if ver else None,
        "operations": ops,
        "schemas": {k: schemas[k] for k in sorted(schemas)},
        "referenced": sorted(models),
    }


def normalize(path: str) -> str:
    """Positional placeholders, lowercased: parameter names and casing differ
    between the SDK and the docs for the same route."""
    return re.sub(r"\{[^}]+\}", "{}", path).lower()


def check(start: pathlib.Path) -> int:
    spec_path = pathlib.Path(__file__).resolve().parent.parent / "oas" / "openapi.json"
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    inv = extract(start)

    sdk = {}
    for o in inv["operations"]:
        sdk.setdefault((o["method"].lower(), normalize(o["path"])), o)
    spec_ops = {}
    for p, item in spec.get("paths", {}).items():
        for verb, op in item.items():
            if verb in ("get", "put", "post", "patch", "delete"):
                spec_ops[(verb, normalize(p))] = (p, op)

    missing = sorted(set(sdk) - set(spec_ops))
    extra = sorted(set(spec_ops) - set(sdk))
    for verb, p in missing:
        print(f"MISSING from spec (SDK has it): {verb.upper()} {sdk[(verb, p)]['path']}")
    for verb, p in extra:
        print(f"NOT IN SDK (docs- or traffic-sourced): {verb.upper()} {spec_ops[(verb, p)][0]}")

    # shared routes: query parameters, and the error status codes Kiota maps
    for key in sorted(set(sdk) & set(spec_ops)):
        op_path, op = spec_ops[key]
        have = {p["name"]: p for p in op.get("parameters", []) if p.get("in") == "query"}
        for q in sdk[key]["query"]:
            if q["name"] not in have:
                print(f"QUERY missing: {key[0].upper()} {op_path} ?{q['name']}")
            elif bool(have[q["name"]].get("required")) != q["required"]:
                print(f"QUERY required={q['required']} in SDK, "
                      f"{bool(have[q['name']].get('required'))} in spec: "
                      f"{key[0].upper()} {op_path} ?{q['name']}")
        for code in sorted(sdk[key]["errors"]):
            if code not in op.get("responses", {}):
                print(f"STATUS undocumented: {key[0].upper()} {op_path} -> {code} "
                      f"({sdk[key]['errors'][code]})")

    # models: the SDK is a second projection of the same internal document, so a
    # disagreement here is a docs-parsing bug, a service change, or (where live
    # traffic already settled it) a spec-versus-implementation split
    spec_schemas = spec.get("components", {}).get("schemas", {})
    for name in sorted(set(inv["schemas"]) & set(spec_schemas)):
        sdk_s, spec_s = inv["schemas"][name], spec_schemas[name]
        if spec_s.get("x-stub"):
            print(f"SCHEMA stub in spec, defined by SDK: {name}")
            continue
        if "enum" in sdk_s:
            extra_vals = [v for v in sdk_s["enum"] if v not in spec_s.get("enum", [])]
            if "enum" not in spec_s:
                print(f"ENUM missing in spec: {name} = {sdk_s['enum']}")
            elif extra_vals:
                print(f"ENUM values only in SDK: {name} += {extra_vals}")
            continue
        spec_props = spec_s.get("properties", {})
        if not spec_props:
            continue
        folded = {k.lower(): k for k in spec_props}
        for prop in sdk_s.get("properties", {}):
            if prop in spec_props:
                continue
            if prop.lower() in folded:
                print(f"CASE differs: {name}.{folded[prop.lower()]} in spec, "
                      f"{prop} in SDK")
            else:
                print(f"PROPERTY only in SDK: {name}.{prop}")

    print(f"\nSDK: {len(sdk)} operations over {len({p for _, p in sdk})} paths, "
          f"{len(inv['schemas'])} models, api-version constant {inv['apiVersion']}")
    print(f"spec: {len(spec_ops)} operations, {len(spec_schemas)} schemas; "
          f"{len(missing)} SDK-only, {len(extra)} spec-only, "
          f"{len(set(inv['schemas']) & set(spec_schemas))} models shared by name")
    return 1 if missing else 0


if __name__ == "__main__":
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args:
        sys.exit(__doc__.strip().splitlines()[-6].strip())
    target = pathlib.Path(args[0])
    if "--check" in sys.argv:
        sys.exit(check(target))
    out = extract(target)
    if "--schemas" in sys.argv:
        out = out["schemas"]
    print(json.dumps(out, indent=1, ensure_ascii=False))
