using System.Text.Json;

namespace PowerPlatformApis.Browser.Model;

/// <summary>
/// A deliberately small OpenAPI 3.0 model over <see cref="JsonElement"/>.
/// Every spec this app renders is generated by this repository in a known
/// shape, so a full OpenAPI library would cost payload and version churn for
/// coverage we do not use. Reading straight from the JSON also means the
/// x- extensions we rely on (x-notes, x-ms-namespace, x-ms-preview) need no
/// mapping.
/// </summary>
public sealed class OpenApiSpec
{
    private readonly JsonElement _root;

    private OpenApiSpec(JsonElement root)
    {
        _root = root;
        Info = new SpecInfo(Obj(root, "info"));
        Servers = Arr(root, "servers").Select(s => Str(s, "url")).Where(u => u is not null).Select(u => u!).ToList();
        Tags = Arr(root, "tags")
            .Select(t => new SpecTag(Str(t, "name") ?? "", Str(t, "description")))
            .ToList();
        Schemas = Obj(root, "components") is { } c && Obj(c, "schemas") is { } s
            ? s.EnumerateObject().ToDictionary(p => p.Name, p => new SchemaRef(p.Value, this), StringComparer.Ordinal)
            : new Dictionary<string, SchemaRef>(StringComparer.Ordinal);

        var ops = new List<Operation>();
        if (Obj(root, "paths") is { } paths)
        {
            foreach (var path in paths.EnumerateObject())
            {
                foreach (var verb in path.Value.EnumerateObject())
                {
                    if (!Methods.Contains(verb.Name)) continue;
                    ops.Add(new Operation(path.Name, verb.Name, verb.Value, this));
                }
            }
        }
        Operations = ops;
    }

    private static readonly HashSet<string> Methods =
        new(StringComparer.OrdinalIgnoreCase) { "get", "put", "post", "delete", "patch", "options", "head", "trace" };

    public SpecInfo Info { get; }
    public IReadOnlyList<string> Servers { get; }
    public IReadOnlyList<SpecTag> Tags { get; }
    public IReadOnlyList<Operation> Operations { get; }
    public IReadOnlyDictionary<string, SchemaRef> Schemas { get; }

    public static OpenApiSpec Parse(string json)
    {
        var doc = JsonDocument.Parse(json);
        return new OpenApiSpec(doc.RootElement.Clone());
    }

    /// <summary>Tags in declared order, then any tag used by an operation but not declared.</summary>
    public IEnumerable<SpecTag> TagsInOrder()
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var t in Tags) { if (seen.Add(t.Name)) yield return t; }
        foreach (var op in Operations)
            foreach (var t in op.Tags)
                if (seen.Add(t)) yield return new SpecTag(t, null);
    }

    public SchemaRef? Resolve(string reference)
    {
        const string prefix = "#/components/schemas/";
        if (!reference.StartsWith(prefix, StringComparison.Ordinal)) return null;
        return Schemas.TryGetValue(reference[prefix.Length..], out var s) ? s : null;
    }

    public static string? SchemaName(string reference)
    {
        const string prefix = "#/components/schemas/";
        return reference.StartsWith(prefix, StringComparison.Ordinal) ? reference[prefix.Length..] : null;
    }

    // ---- JsonElement helpers, shared with the types below ----
    internal static JsonElement? Obj(JsonElement e, string name) =>
        e.ValueKind == JsonValueKind.Object && e.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.Object ? v : null;

    internal static IEnumerable<JsonElement> Arr(JsonElement e, string name) =>
        e.ValueKind == JsonValueKind.Object && e.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.Array
            ? v.EnumerateArray() : Enumerable.Empty<JsonElement>();

    internal static string? Str(JsonElement e, string name) =>
        e.ValueKind == JsonValueKind.Object && e.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString() : null;

    internal static bool Bool(JsonElement e, string name) =>
        e.ValueKind == JsonValueKind.Object && e.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.True;

    internal static IReadOnlyList<string> StrArr(JsonElement e, string name) =>
        Arr(e, name).Where(x => x.ValueKind == JsonValueKind.String).Select(x => x.GetString()!).ToList();
}

public sealed record SpecTag(string Name, string? Description)
{
    public string Slug => Slugify(Name);

    public static string Slugify(string s)
    {
        var chars = s.ToLowerInvariant().Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray();
        return string.Join('-', new string(chars).Split('-', StringSplitOptions.RemoveEmptyEntries));
    }
}

public sealed class SpecInfo
{
    public SpecInfo(JsonElement? info)
    {
        var e = info ?? default;
        Title = OpenApiSpec.Str(e, "title") ?? "API";
        Version = OpenApiSpec.Str(e, "version");
        Description = OpenApiSpec.Str(e, "description");
        ApiVersions = OpenApiSpec.StrArr(e, "x-api-versions");
    }

    public string Title { get; }
    public string? Version { get; }
    public string? Description { get; }
    public IReadOnlyList<string> ApiVersions { get; }
}

public sealed class Operation
{
    private readonly JsonElement _e;

    public Operation(string path, string method, JsonElement e, OpenApiSpec spec)
    {
        _e = e;
        Path = path;
        Method = method.ToUpperInvariant();
        OperationId = OpenApiSpec.Str(e, "operationId") ?? $"{method}{path}";
        Summary = OpenApiSpec.Str(e, "summary") ?? OperationId;
        Description = OpenApiSpec.Str(e, "description");
        Tags = OpenApiSpec.StrArr(e, "tags");
        Namespace = OpenApiSpec.Str(e, "x-ms-namespace");
        IsPreview = OpenApiSpec.Bool(e, "x-ms-preview");
        Notes = OpenApiSpec.StrArr(e, "x-notes");
        DocsUrl = OpenApiSpec.Obj(e, "externalDocs") is { } ed ? OpenApiSpec.Str(ed, "url") : null;
        Parameters = OpenApiSpec.Arr(e, "parameters").Select(p => new Parameter(p, spec)).ToList();

        if (OpenApiSpec.Obj(e, "requestBody") is { } rb)
            RequestBody = new Body(rb, spec);

        Responses = OpenApiSpec.Obj(e, "responses") is { } rs
            ? rs.EnumerateObject().Select(p => new Response(p.Name, p.Value, spec)).OrderBy(r => r.Code, StringComparer.Ordinal).ToList()
            : new List<Response>();
    }

    public string Path { get; }
    public string Method { get; }
    public string OperationId { get; }
    public string Summary { get; }
    public string? Description { get; }
    public IReadOnlyList<string> Tags { get; }
    public string? Namespace { get; }
    public bool IsPreview { get; }
    public IReadOnlyList<string> Notes { get; }
    public string? DocsUrl { get; }
    public IReadOnlyList<Parameter> Parameters { get; }
    public Body? RequestBody { get; }
    public IReadOnlyList<Response> Responses { get; }

    public string PrimaryTag => Tags.Count > 0 ? Tags[0] : "Other";

    /// <summary>The description with any note blockquote removed; notes render as their own callout.</summary>
    public string? Prose
    {
        get
        {
            if (Description is null) return null;
            var lines = Description.Split('\n');
            var kept = lines.TakeWhile(l => !l.TrimStart().StartsWith(">", StringComparison.Ordinal));
            var text = string.Join('\n', kept).Trim();
            return text.Length == 0 ? null : text;
        }
    }
}

public sealed class Parameter
{
    public Parameter(JsonElement e, OpenApiSpec spec)
    {
        Name = OpenApiSpec.Str(e, "name") ?? "";
        In = OpenApiSpec.Str(e, "in") ?? "query";
        Required = OpenApiSpec.Bool(e, "required");
        Description = OpenApiSpec.Str(e, "description");
        Schema = e.TryGetProperty("schema", out var s) ? new SchemaRef(s, spec) : null;
    }

    public string Name { get; }
    public string In { get; }
    public bool Required { get; }
    public string? Description { get; }
    public SchemaRef? Schema { get; }
}

public sealed class Body
{
    public Body(JsonElement e, OpenApiSpec spec)
    {
        Required = OpenApiSpec.Bool(e, "required");
        Description = OpenApiSpec.Str(e, "description");
        if (OpenApiSpec.Obj(e, "content") is { } content)
        {
            var first = content.EnumerateObject().FirstOrDefault();
            if (first.Value.ValueKind == JsonValueKind.Object)
            {
                MediaType = first.Name;
                if (first.Value.TryGetProperty("schema", out var s)) Schema = new SchemaRef(s, spec);
            }
        }
    }

    public bool Required { get; }
    public string? Description { get; }
    public string? MediaType { get; }
    public SchemaRef? Schema { get; }
}

public sealed class Response
{
    public Response(string code, JsonElement e, OpenApiSpec spec)
    {
        Code = code;
        Description = OpenApiSpec.Str(e, "description");
        if (OpenApiSpec.Obj(e, "content") is { } content)
        {
            var first = content.EnumerateObject().FirstOrDefault();
            if (first.Value.ValueKind == JsonValueKind.Object && first.Value.TryGetProperty("schema", out var s))
            {
                MediaType = first.Name;
                Schema = new SchemaRef(s, spec);
            }
        }
        Headers = OpenApiSpec.Obj(e, "headers") is { } h
            ? h.EnumerateObject().Select(p => new Header(p.Name, p.Value, spec)).ToList()
            : new List<Header>();
    }

    public string Code { get; }
    public string? Description { get; }
    public string? MediaType { get; }
    public SchemaRef? Schema { get; }
    public IReadOnlyList<Header> Headers { get; }

    public bool IsSuccess => Code.StartsWith('2');
    public bool IsError => Code.StartsWith('4') || Code.StartsWith('5');
}

public sealed class Header
{
    public Header(string name, JsonElement e, OpenApiSpec spec)
    {
        Name = name;
        Description = OpenApiSpec.Str(e, "description");
        Schema = e.TryGetProperty("schema", out var s) ? new SchemaRef(s, spec) : null;
    }

    public string Name { get; }
    public string? Description { get; }
    public SchemaRef? Schema { get; }
}
